base_url = "https://azohra.com"
title = "Azohra"

compile_sass = true

highlight_code = false

build_search_index = false

[extra]
greeting = "Azohra"

iam = "Video Editing"

links = [
    { title = "E-Mail", url = "mailto:editing@azohra.com", iconset = "fas", icon = "envelope" },
    { title = "Facebook", url = "https://www.facebook.com/Azohra-171099103607342", icon = "facebook" },
    { title = "Twitter", url = "https://www.youtube.com/channel/UC4s7PpGMGYf1UOxNM1o8Y6Q", icon = "youtube" },
    { title = "Twitter", url = "https://www.instagram.com/editingbyazohra/", icon = "instagram" }
]

[extra.author]
name = ""

[extra.theme]
background = "#000"
foreground = "#FFF"
hover = "#333"
